[package]
name = "dolly-sbf-rust-simulation"
description = "Solana SBF Program Simulation Differences"
documentation = "https://docs.rs/dolly-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
dolly-program = { workspace = true }

[dev-dependencies]
dolly-logger = { workspace = true }
dolly-program-test = { workspace = true }
dolly-sdk = { workspace = true }
dolly-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
