[package]
name = "dolly-unified-scheduler-logic"
description = "The Solana unified scheduler logic"
documentation = "https://docs.rs/dolly-unified-scheduler-logic"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
dolly-sdk = { workspace = true }
