[package]
name = "dolly-stake-program"
description = "Solana Stake program"
documentation = "https://docs.rs/dolly-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
dolly-config-program = { workspace = true }
dolly-program-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
dolly-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "dolly_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
