[package]
name = "dolly-rpc"
description = "Solana RPC"
documentation = "https://docs.rs/dolly-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
dolly-account-decoder = { workspace = true }
dolly-accounts-db = { workspace = true }
dolly-client = { workspace = true }
dolly-entry = { workspace = true }
dolly-faucet = { workspace = true }
dolly-gossip = { workspace = true }
dolly-ledger = { workspace = true }
dolly-measure = { workspace = true }
dolly-metrics = { workspace = true }
dolly-perf = { workspace = true }
dolly-poh = { workspace = true }
dolly-rayon-threadlimit = { workspace = true }
dolly-rpc-client-api = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-send-transaction-service = { workspace = true }
dolly-stake-program = { workspace = true }
dolly-storage-bigtable = { workspace = true }
dolly-streamer = { workspace = true }
dolly-svm = { workspace = true }
dolly-tpu-client = { workspace = true }
dolly-transaction-status = { workspace = true }
dolly-version = { workspace = true }
dolly-vote = { workspace = true }
dolly-vote-program = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }
dolly-stake-program = { workspace = true }
spl-pod = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "dolly_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
