[package]
name = "dolly-transaction-dos"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-cli = { workspace = true }
dolly-client = { workspace = true }
dolly-core = { workspace = true }
dolly-faucet = { workspace = true }
dolly-gossip = { workspace = true }
dolly-logger = { workspace = true }
dolly-measure = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-rpc-client = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-streamer = { workspace = true }
dolly-transaction-status = { workspace = true }
dolly-version = { workspace = true }

[dev-dependencies]
dolly-local-cluster = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
