[package]
name = "dolly-validator"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/dolly-validator"
default-run = "dolly-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
dolly-accounts-db = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-cli-config = { workspace = true }
dolly-core = { workspace = true }
dolly-download-utils = { workspace = true }
dolly-entry = { workspace = true }
dolly-faucet = { workspace = true }
dolly-genesis-utils = { workspace = true }
dolly-geyser-plugin-interface = { workspace = true }
dolly-geyser-plugin-manager = { workspace = true }
dolly-gossip = { workspace = true }
dolly-ledger = { workspace = true }
dolly-logger = { workspace = true }
dolly-metrics = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-perf = { workspace = true }
dolly-poh = { workspace = true }
dolly-program-runtime = { workspace = true }
dolly-rayon-threadlimit = { workspace = true }
dolly-rpc = { workspace = true }
dolly-rpc-client = { workspace = true }
dolly-rpc-client-api = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-send-transaction-service = { workspace = true }
dolly-storage-bigtable = { workspace = true }
dolly-streamer = { workspace = true }
dolly-test-validator = { workspace = true }
dolly-tpu-client = { workspace = true }
dolly-unified-scheduler-pool = { workspace = true }
dolly-version = { workspace = true }
dolly-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
dolly-account-decoder = { workspace = true }
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
