[package]
name = "dolly-gossip"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/dolly-gossip"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
bv = { workspace = true, features = ["serde"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
flate2 = { workspace = true }
indexmap = { workspace = true, features = ["rayon"] }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
rustversion = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_derive = { workspace = true }
dolly-bloom = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-client = { workspace = true }
dolly-connection-cache = { workspace = true }
dolly-entry = { workspace = true }
dolly-frozen-abi = { workspace = true }
dolly-frozen-abi-macro = { workspace = true }
dolly-ledger = { workspace = true }
dolly-logger = { workspace = true }
dolly-measure = { workspace = true }
dolly-metrics = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-perf = { workspace = true }
dolly-rayon-threadlimit = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-streamer = { workspace = true }
dolly-tpu-client = { workspace = true }
dolly-version = { workspace = true }
dolly-vote = { workspace = true }
dolly-vote-program = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
num_cpus = { workspace = true }
serial_test = { workspace = true }
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bin]]
name = "dolly-gossip"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
