[package]
name = "dolly-compute-budget-program"
description = "Solana Compute Budget program"
documentation = "https://docs.rs/dolly-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
dolly-program-runtime = { workspace = true }
dolly-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "dolly_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
