[package]
name = "dolly-udp-client"
description = "Solana UDP Client"
documentation = "https://docs.rs/dolly-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
dolly-connection-cache = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-sdk = { workspace = true }
dolly-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
