[package]
name = "dolly-unified-scheduler-pool"
description = "The Solana unified scheduler pool"
documentation = "https://docs.rs/dolly-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }
dolly-ledger = { workspace = true }
dolly-program-runtime = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-unified-scheduler-logic = { workspace = true }
dolly-vote = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
dolly-logger = { workspace = true }
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }
