[package]
name = "dolly-stake-accounts"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/dolly-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-cli-config = { workspace = true }
dolly-remote-wallet = { workspace = true, features = ["default"] }
dolly-rpc-client = { workspace = true, features = ["default"] }
dolly-rpc-client-api = { workspace = true }
dolly-sdk = { workspace = true }
dolly-stake-program = { workspace = true }
dolly-version = { workspace = true }

[dev-dependencies]
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
