[package]
name = "dolly-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/dolly-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-cli-config = { workspace = true }
dolly-cli-output = { workspace = true }
dolly-logger = { workspace = true }
dolly-metrics = { workspace = true }
dolly-notifier = { workspace = true }
dolly-rpc-client = { workspace = true }
dolly-rpc-client-api = { workspace = true }
dolly-sdk = { workspace = true }
dolly-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
