[package]
name = "dolly-tokens"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/dolly-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
dolly-account-decoder = { workspace = true }
dolly-clap-utils = { workspace = true }
dolly-cli-config = { workspace = true }
dolly-remote-wallet = { workspace = true, features = ["default"] }
dolly-rpc-client = { workspace = true, features = ["default"] }
dolly-rpc-client-api = { workspace = true }
dolly-sdk = { workspace = true }
dolly-transaction-status = { workspace = true }
dolly-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
dolly-logger = { workspace = true }
dolly-streamer = { workspace = true }
dolly-test-validator = { workspace = true }
