[package]
name = "dolly-quic-client"
description = "Solana Quic Client"
documentation = "https://docs.rs/dolly-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
dolly-connection-cache = { workspace = true }
dolly-measure = { workspace = true }
dolly-metrics = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-rpc-client-api = { workspace = true }
dolly-sdk = { workspace = true }
dolly-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
dolly-logger = { workspace = true }
dolly-perf = { workspace = true }
