[package]
name = "dolly-poh-bench"
documentation = "https://docs.rs/dolly-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
dolly-entry = { workspace = true }
dolly-logger = { workspace = true }
dolly-measure = { workspace = true }
dolly-perf = { workspace = true }
dolly-sdk = { workspace = true }
dolly-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
