# This package only exists to avoid circular dependencies during cargo publish:
# dolly-runtime -> dolly-address-program -> dolly-program-test -> dolly-runtime

[package]
name = "dolly-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
dolly-address-lookup-table-program = { workspace = true }
dolly-program-test = { workspace = true }
dolly-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
