[package]
name = "dolly-test-validator"
description = "Blockchain, Rebuilt for Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
dolly-accounts-db = { workspace = true }
dolly-cli-output = { workspace = true }
dolly-client = { workspace = true }
dolly-core = { workspace = true }
dolly-geyser-plugin-manager = { workspace = true }
dolly-gossip = { workspace = true }
dolly-ledger = { workspace = true }
dolly-logger = { workspace = true }
dolly-net-utils = { workspace = true }
dolly-program-runtime = { workspace = true }
dolly-program-test = { workspace = true }
dolly-rpc = { workspace = true }
dolly-rpc-client = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-streamer = { workspace = true }
dolly-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
