[package]
name = "dolly-system-program"
description = "Solana System program"
documentation = "https://docs.rs/dolly-system-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
dolly-program-runtime = { workspace = true }
dolly-sdk = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
dolly-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "dolly_system_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
