[package]
name = "dolly-send-transaction-service"
description = "Solana send transaction service"
documentation = "https://docs.rs/dolly-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
dolly-client = { workspace = true }
dolly-measure = { workspace = true }
dolly-metrics = { workspace = true }
dolly-runtime = { workspace = true }
dolly-sdk = { workspace = true }
dolly-tpu-client = { workspace = true }

[dev-dependencies]
dolly-logger = { workspace = true }
dolly-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
